name: PR Test with Secrets
on:
  workflow_run:
    workflows: ["PR External Build"]
    types:
      - completed

jobs:
  approve-and-test:
    name: E2E Tests (Requires Approval)
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    environment: pull-request-e2e
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download PR info
        uses: actions/github-script@v7
        id: pr-info
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            return context.payload.workflow_run.pull_requests[0].number;

      - name: Install earthly
        run: sudo bash -c "curl -L https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -o /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly"

      - name: Run E2E Tests
        run: |
          earthly --secret TOPK_API_KEY +test-rs --region elastica
          earthly --secret TOPK_API_KEY +test-py --region elastica
          earthly --secret TOPK_API_KEY +test-js --region elastica
        env:
          TOPK_API_KEY: ${{ secrets.TOPK_API_KEY }}